export const uodosTranslations = {
     uodo: 'Zgłaszanie naruszeń danych osobowych',
     newBreadCrumb: 'Zgłoszenie naruszenia danych osobowych',
     section1: '1.	Typ zgłoszenia',
     section1Desc:
          'Wskaż czy zgłaszasz naruszenie ochrony danych osobowych mające charakter jednorazowego zdarzenia (np. zgubienie, kradzież nośnika danych, przypadkowe wysłanie danych osobie nieuprawnionej), czy przygotowujesz wstępne zgłoszenie, które uzupełnisz później, lub czy uzupełniasz lub zmieniasz wcześniejsze zgłoszenie.',
     optionalSign: 'Podaj swoją sygnaturę sprawy (opcjonalnie)',
     registrationComplet: 'Zgłoszenie kompletne/jednorazowe',
     registrationBegin: 'Zgłoszenie wstępne',
     registrationCompletModify: 'Zgłoszenie uzupełniające/zmieniające',
     optionalSignfooter: '(np. sygnatura w Twoim wewnętrznym rejestrze naruszeń)',
     placeholderClickAddText: 'Kliknij tutaj, aby wprowadzić tekst.',
     addDateReopen: 'Podaj przybliżoną datę uzupełnienia zgłoszenia (opcjonalnie)',
     placeholderclickAddDate: 'Kliknij tutaj, aby wprowadzić datę.',
     addDateOld: 'Podaj datę poprzedniego zgłoszenia (opcjonalnie)',
     addTaskSignUodo: 'Podaj sygnaturę sprawy UODO',
     theViolationHasBeenReportedOtherCoutry:
          'Naruszenie zostało lub zostanie zgłoszone organowi ochrony danych osobowych w innym państwie',
     placeholderWithCoutry: 'Jeśli tak, podaj w jakim.',
     theViolationHasBeenReported:
          'Naruszenie zostało lub zostanie zgłoszone innym organom np. Policja, CSIRT NASK, CSIRT GOV, CSIRT MON (najedź myszką na nazwę organu by dowiedzieć się więcej)',
     addNameDepart: 'Podaj nazwy tych organów',
     addSignatureRegistration: 'Podaj numer/sygnaturę zgłoszenia do innego organu',
     section2: '2.	Podmiot zgłaszający',
     section2a: '2A. Dane administratora danych',
     fullNameAdmin: 'Pełna nazwa administratora',
     placeholderaddNumber: 'Podaj numer.',
     regon: 'REGON (opcjonalnie)',
     nip: 'NIP (opcjonalnie)',
     krs: 'KRS (opcjonalnie)',
     sector: 'Sektor (opcjonalnie)',
     forSectorPublic: 'Dla sektora publicznego: ',
     placeholderChooseElement: 'Wybierz element.',
     forSectorPrivate: 'Dla sektora prywatnego: ',
     section2b: '2B. Adres siedziby administratora danych',
     street: 'Ulica',
     numberHouse: 'Numer domu',
     numberflat: 'Numer lokalu',
     city: 'Miejscowość',
     postCode: 'Kod pocztowy',
     provinceAdministrativeArea: 'Województwo',
     countyAdministrativeArea: 'Powiat',
     communeAdministrativeArea: 'Gmina',
     country: 'Państwo',
     section2c: '2C. Osoby uprawnione do reprezentowania administratora',
     nameAndSurname2f: 'Nazwa i dane kontaktowe',
     addNewContactPerson2C: 'Dodaj osobę uprawnioną do repezentowania administartora',
     addNewContactPerson2f: 'Dodaj inny podmiot, którego dotyczy naruszenie',
     editContactPerson2C: 'Edytuj osobę uprawnioną do repezentowania administartora',
     editContactPerson2f: 'Edytuj inny podmiot, którego dotyczy naruszenie',
     position: 'Stanowisko',
     addNextPerson:
          '(Aby dopisać kolejne osoby, należy po kliknięciu na powyższe pole kliknąć przycisk, który pojawi się po prawej stronie)',
     section2d: '2D. Pełnomocnik',
     applicationCompletedTheRepresentative: 'Wniosek wypełniany przez pełnomocnika (opcjonalnie)',
     descriotionSection2d:
          'Jeśli zgłoszenie przesyłane jest w formie elektronicznej, należy załączyć pełnomocnictwo udzielone w formie elektronicznej oraz dowód uiszczenia opłaty skarbowej',
     section2e: '2E. Inspektor ochrony danych',
     dataProtectionOfficer: 'Imię i nazwisko',
     phoneNumber: 'Numer telefonu',
     placeholerNumberPhone: 'Numer telefonu.',
     mail: 'Adres e-mail',
     placeholderMail: 'E-mail.',
     anInspectorHasNotBeenAppointed: 'Inspektor nie został wyznaczony',
     descriotionSection2e:
          'Jeśli inspektor nie został wyznaczony podaj dane innego punktu kontaktowego, od którego można uzyskać więcej informacji o naruszeniu.',
     section2f:
          '2F. Inne podmioty uczestniczące w przetwarzaniu danych, których dotyczy naruszenie (opcjonalnie)',
     descriptionSection2f:
          'Podaj nazwy podmiotów, dane kontaktowe i wyjaśnij ich rolę w procesie przetwarzania, którego dotyczy naruszenie (np. podmiot przetwarzający, współadministratora, operator pocztowy itp.)',
     nameDateContact: 'Imię i nazwisko',
     role: 'Rola',
     addNextSubject:
          '(Aby dopisać kolejne podmioty, należy po kliknięciu na powyższe pole kliknąć przycisk, który pojawi się po prawej stronie)',
     section3: '3.	Czas naruszenia',
     section3a: '3A. Wykrycie naruszenia i powiadomienie organu nadzorczego',
     dateDiscoveryInfringement: 'Data stwierdzenia naruszenia',
     descriptionDateDiscoveryInfringement:
          'Wskaż kiedy dowiedziałeś/aś się o naruszeniu. Jeśli nie znasz dokładnego terminu, podaj czas przybliżony.',
     methodDeterminingViolation: 'Sposób stwierdzenia naruszenia',
     descriptionMethodDeterminingViolation:
          'Np. zgłoszenie osoby której dane dotyczą czy cykliczny przegląd logów systemowych zgodnie z wdrożoną polityką bezpieczeństwa',
     dateInformationSubject: 'Data powiadomienia przez podmiot przetwarzający (opcjonalnie)',
     descriptionDateInformationSubject: 'Jeśli nie znasz dokładnego terminu, podaj czas przybliżony.',
     reasonsForDelay: 'Powody opóźnienia powiadomienia organu nadzorczego o naruszeniu',
     descriptionReasonsForDelay:
          'Pole obowiązkowe jeśli czas od momentu stwierdzenia naruszenia do czasu wypełniania formularza jest dłuższy niż 72h',
     section3b: '3B. Czas naruszenia',
     dateTime3b: 'Data i czas zaistnienia/rozpoczęcia naruszenia',
     descriptionDateTime: 'Jeśli nie znasz dokładnego terminu, podaj czas przybliżony.',
     dateTimeEnd3b: 'Data i czas zakończenia naruszenia (opcjonalnie)',
     descriptionDateTimeEnd: 'Jeśli nie znasz dokładnego terminu, podaj czas przybliżony.',
     section4: '4.	Charakter naruszenia',
     section4a: '4A. Opisz szczegółowo na czym polegało naruszenie',
     descSection4a: 'Opis: ',
     section4b: '4B. Na czym polegało naruszenie?',
     section4bcheckboxA: 'a) Zgubienie lub kradzież nośnika/urządzenia',
     section4bcheckboxB:
          'b) Dokumentacja papierowa (zawierająca dane osobowe) zgubiona, skradziona lub pozostawiona w niezabezpieczonej lokalizacji',
     section4bcheckboxC:
          'c) Korespondencja papierowa utracona przez operatora pocztowego lub otwarta przed zwróceniem jej do nadawcy',
     section4bcheckboxD: 'd) Nieuprawnione uzyskanie dostępu do informacji',
     section4bcheckboxE: 'e) Nieuprawnione uzyskanie dostępu do informacji poprzez złamanie zabezpieczeń',
     section4bcheckboxF:
          'f) Złośliwe oprogramowanie ingerujące w poufność, integralność lub dostępność danych',
     section4bcheckboxG:
          'g) Uzyskanie poufnych informacji przez pozornie zaufaną osobę w oficjalnej komunikacji elektronicznej, takiej jak e-mail czy komunikator internetowy (phishing)',
     section4bcheckboxH: 'h) Nieprawidłowa anonimizacja danych osobowych w dokumencie',
     section4bcheckboxI:
          'i) Nieprawidłowe usunięcie/zniszczenie danych osobowych z nośnika/urządzenia elektronicznego przed jego zbyciem przez administratora',
     section4bcheckboxJ: 'j) Niezamierzona publikacja',
     section4bcheckboxK: 'k) Dane osobowe wysłane do niewłaściwego odbiorcy',
     section4bcheckboxL: 'l) Ujawnienie danych niewłaściwej osoby',
     section4bcheckboxM: 'm) Ustne ujawnienie danych osobowych',
     section4c:
          '4C. Działanie złośliwego oprogramowania (odpowiedz na poniższe pytania, jeśli w sekcji 4B zaznaczono pole f)',
     descriptionSection4Ca:
          'a)	Jeśli w ocenie administratora doszło wyłącznie do naruszenia dostępności danych, w jaki sposób stwierdzono, że nie doszło do naruszenia ich poufności? (w sytuacji gdy np. dane nie zostały pobrane przez osobę nieupoważnioną, a jedynie zaszyfrowane w sposób uniemożliwiający uzyskanie do nich dostępu)',
     descriptionSection4Cb:
          'b)	Czy, a jeżeli tak, to w jakiej formie, złośliwe oprogramowanie poinformowało o konieczności uiszczenia opłaty w celu odzyskania dostępu do danych (podaj nazwę złośliwego oprogramowania, sposób poinformowania, żądaną kwotę, kanał komunikacji, sposób zapłaty oraz termin)',
     descriptionSection4Cc:
          'c)	Jeżeli doszło do utraty dostępności danych, to czy administrator był w posiadaniu kopii zapasowej, jeśli tak to w jakim czasie ją przywrócił?',
     descriptionSection4CAttencion:
          'UWAGA: Jeżeli zgłoszenie naruszenia dotyczy podejrzanych załączników, phishingu, szantażu czy działania złośliwego oprogramowania, rozważ zgłoszenie zdarzenia do CERT Polska pod adresem https://incydent.cert.pl/. Dokonanie takiego zgłoszenia jest szczególnie zalecane w przypadku, kiedy odpowiedzi na powyższe pytania są utrudnione bądź niemożliwe. O fakcie zgłoszenia incydentu do CERT Polska poinformuj w zgłoszeniu uzupełniającym Prezesa UODO (pkt 1 formularza) podając datę zgłoszenia, jego numer oraz ewentualnie informacje na temat incydentu otrzymane od CERT Polska.',
     section4d: '4D. Przyczyna naruszenia',
     internalActionUnintentional: 'Wewnętrzne działanie niezamierzone',
     internalActionIntentional: 'Wewnętrzne działanie zamierzone',
     externalActionUnintentional: 'Zewnętrzne działanie niezamierzone',
     externalActionIntentional: 'Zewnętrzne działanie zamierzone',
     section4e: '4E. Charakter',
     breachOfDataConfidentiality: 'Naruszenie poufności danych',
     descbreachOfDataConfidentiality: 'Nieuprawnione lub przypadkowe ujawnienie bądź udostępnienie danych',
     dataIntegrityBreach: 'Naruszenie integralności danych',
     descDataIntegrityBreach:
          'Wprowadzenie nieuprawnionych zmian podczas odczytu, zapisu, transmisji lub przechowywania',
     dataAvailabilityViolation: 'Naruszenie dostępności danych',
     descDataAvailabilityViolation:
          'Brak możliwości wykorzystania danych na żądanie, w założonym czasie, przez osobę do tego uprawnioną',
     section4f: '4F. Dzieci',
     section4FKids:
          'Naruszenie dotyczy przetwarzania danych w związku ze świadczeniem usług społeczeństwa informacyjnego oferowanych bezpośrednio dziecku.',
     section5: '5.	Liczba osób i wpisów',
     approximateNumberOfPeopleBreached: 'Przybliżona liczba osób, których dotyczy naruszenie',
     approximateNumberOfPeopleBreachedEntry:
          'Przybliżona liczba wpisów danych osobowych, których dotyczy naruszenie. ',
     descapproximateNumberOfPeopleBreachedEntry:
          'Nie dotyczy to liczby osób. Jednej osobie można przypisać kilka wpisów (np. jednej osobie można przypisać kilka wykonanych transakcji)',
     section6: '6.	Kategorie danych osobowych',
     section6Attention:
          'UWAGA: W zgłoszeniu nie podawaj danych konkretnych osób, których dotyczy naruszenie.',
     section6a: '6A. Dane podstawowe',
     surnamesAndNames: 'Nazwiska i imiona',
     namesParents: 'Imiona rodziców',
     birthData: 'Data urodzenia',
     numberaAccountBank: 'Numer rachunku bankowego',
     adressliving: 'Adres zamieszkania lub pobytu',
     pesel: 'Numer ewidencyjny PESEL',
     addressMail: 'Adres e-mail',
     loginPassword: 'Nazwa użytkownika i/lub hasło',
     dataFromMoney: 'Dane dotyczące zarobków i/lub posiadanego majątku',
     surnameMother: 'Nazwisko rodowe matki',
     serialNumberPersonallDocument: 'Seria i numer dowodu osobistego',
     phoneNumer: 'Numer telefonu',
     imagePerson: 'Wizerunek',
     other: 'Inne, wskaż jakie: ',
     section6b: '6B. Dane szczególnej kategorii',
     dataAboutRacialEthnicOrigin: 'Dane o pochodzeniu rasowym lub etnicznym',
     dataAboutPolitic: 'Dane o poglądach politycznych',
     dataAboutReligion: 'Dane o przekonaniach religijnych lub światopoglądowych',
     dataAboutSocjal: 'Dane o przynależności do związków zawodowych',
     dataAboutSexual: 'Dane dotyczące seksualności lub orientacji seksualnej',
     dataAboutHealth: 'Dane dotyczące zdrowia',
     dataAboutGenetic: 'Dane genetyczne',
     dataAboutBiometric: 'Dane biometryczne w celu jednoznacznego zidentyfikowania osoby fizycznej',
     section6c: '6C. Dane, o których mowa w art. 10 RODO',
     dataAboutGuiltyverdicts: 'Dane dotyczące wyroków skazujących',
     dataAboutProhibitedActs: 'Dane dotyczące czynów zabronionych',
     dataAboutOther: 'Inne',
     section7: '7.	Kategorie osób',
     employes: 'Pracownicy',
     users: 'Użytkownicy',
     subscribers: 'Subskrybenci',
     studentsHightSchool: 'Studenci',
     students: 'Uczniowie',
     uniformedServices: 'Służby mundurowe (np. wojsko, policja)',
     customers: 'Klienci (obecni i potencjalni)',
     customersPublic: 'Klienci podmiotów publicznych',
     patients: 'Pacjenci',
     kids: 'Dzieci',
     peopleWithSpecialNeeds: 'Osoby o szczególnych potrzebach (np. osoby starsze, niepełnosprawne itp.)',
     detailedDescriptionOfCategoriesPersonsAffectedThebreach:
          'Szczegółowy opis kategorii osób, których dotyczy naruszenie: ',
     descDetailedDescriptionOfCategoriesPersonsAffectedThebreach:
          'Opisz np. kogo i w jakim przedziale czasowym dotyczy naruszenie. W zgłoszeniu nie podawaj danych konkretnych osób, których dotyczy naruszenie.',
     section8: '8.	Możliwe konsekwencje',
     section8a:
          '8A. Uszczerbek fizyczny, majątkowy, niemajątkowy lub inne znaczące konsekwencje dla osoby, której dane dotyczą',
     lossControlOverPersonalData: 'Utrata kontroli nad własnymi danymi osobowymi',
     limitationAbilityToExerciseRightsRodo: 'Ograniczenie możliwości realizowania praw z art. 15-22 RODO',
     limitationAbilityToExerciseRights: 'Ograniczenie możliwości realizowania praw',
     discrimination: 'Dyskryminacja',
     identityTheftFraud: 'Kradzież lub sfałszowanie tożsamości',
     financialLoss: 'Strata finansowa',
     infringementGoodName: 'Naruszenie dobrego imienia',
     lossConfidentialityPersonalDataProtectedProfessionalSecrecy:
          'Utrata poufności danych osobowych chronionych tajemnicą zawodową',
     unauthorizedReversalPseudonymization: 'Nieuprawnione odwrócenie pseudonimizacji',
     section8aOthers: 'Inne',
     descWritelaw:
          'Opisz poniżej inne skutki naruszenia prawa do ochrony danych osoby, której dane dotyczą: ',
     section8b: '8B. Czy wystąpiło wysokie ryzyko naruszenia praw lub wolności osób fizycznych?',
     section8Btrue: 'Tak',
     section8Bfalse: 'Nie',
     justification: 'Uzasadnienie',
     section9: '9.	Środki bezpieczeństwa i środki zaradcze',
     section9a:
          '9A. Ogólny opis technicznych i organizacyjnych środków bezpieczeństwa dotychczas stosowanych',
     section9b:
          '9B. Środki bezpieczeństwa zastosowane lub proponowane w celu zminimalizowana ryzyka ponownego wystąpienia naruszenia',
     section9c:
          '9C. Środki zastosowane lub proponowane w celu zaradzenia naruszeniu i zminimalizowania negatywnych skutków dla osób, których dane dotyczą',
     section10: '10.	Czy osoby, których dane dotyczą, zostały zawiadomione o naruszeniu?',
     section10Notice: 'Nie, ale zostaną zawiadomione',
     section10true: 'Tak',
     section10IndwidualTrue: 'Tak',
     descSection10Notice: 'Pamiętaj, że po powiadomieniu osób, należy przesłać treść zawiadomienia do uodos.',
     indvidual: 'Czy indywidualnie?',
     section10IndwidualFalse:
          'Nie, gdyż indywidualne zawiadomienie każdej osoby, której dane dotyczą wymagałoby niewspółmiernie dużego wysiłku. W związku z tym został bądź zostanie wydany publiczny komunikat lub zastosowany podobny środek, za pomocą którego osoby, których dane dotyczą, zostały bądź zostaną poinformowane w równie skuteczny sposób.',
     theyWillNotBeNotifiedBecause: 'Nie, nie zostaną zawiadomione, ponieważ: ',
     ihaventRatedItYet: 'Nie oceniłem jeszcze',
     descIhaventRatedItYet:
          'Jeśli jeszcze nie oceniłeś czy zamierzasz, zawiadomić osoby, których dane dotyczą, pamiętaj, że po podjęciu takiej decyzji będziesz musiał złożyć zgłoszenie uzupełniające.',
     appropriateTechnicalMeasuresHaveBeenImplementedBeforeTheViolation:
          'przed naruszeniem wdrożono odpowiednie techniczne i organizacyjne środki ochrony (wskazane w pkt.9A formularza) i środki te zostały zastosowane do danych osobowych, których dotyczy naruszenie, w szczególności środki takie jak szyfrowanie, anonimizacji  czy pseudonimizacji uniemożliwiające odczyt osobom nieuprawnionym do dostępu do tych danych osobowych.',
     measuresWereTakenFollowingTheBreach:
          'po naruszeniu zastosowano środki (wskazane w pkt.9C formularza) eliminujące prawdopodobieństwo wysokiego ryzyka naruszenia praw lub wolności osoby, której dotyczą.',
     noHighRiskWasFound:
          'stwierdzono brak wysokiego ryzyka naruszenia praw lub wolności osób fizycznych (uzasadnienie  pkt. 8B formularza)',
     indicateTheDateNotification: 'Wskaż datę zawiadomienia',
     indicateTheDateOfThePlannedNotification: 'Wskaż datę planowanego zawiadomienia',
     numberOfPeopleNotified: 'Liczba zawiadomionych osób',
     iDoNotYetKnowDateWhenIntendToNotifyDataSubjects:
          'Nie znam jeszcze daty kiedy zamierzam zawiadomić osoby, której dane dotyczą',
     meansOfCommunicationUsedToNotifyDataSubject:
          'Środki komunikacji wykorzystywane do zawiadomienia osoby, której dane dotyczą',
     includeDheAnonymized:
          'Umieść zanonimizowaną treść zawiadomienia, którą przesłałeś bądź zamierzasz przesłać do osób, które dane dotyczą ',
     desIncludeDheAnonymized0: 'Pamiętaj, że zawiadomienie powinno: ',
     desIncludeDheAnonymized1:
          '1. opisywać jasnym i prostym językiem charakter naruszenia ochrony danych osobowych,',
     desIncludeDheAnonymized2:
          '2. zawierać imię i nazwisko oraz dane kontaktowe inspektora ochrony danych lub oznaczenie innego punktu kontaktowego, od którego można uzyskać więcej informacji,',
     desIncludeDheAnonymized3: '3. opisywać możliwe konsekwencje naruszenia ochrony danych osobowych,',
     desIncludeDheAnonymized4:
          '4. opisywać środki zastosowane lub proponowane przez administratora w celu zaradzenia naruszeniu ochrony danych osobowych, w tym stosownych przypadkach środki w celu zminimalizowania jego ewentualnych negatywnych skutków.',
     section11: '11.	Przetwarzanie transgraniczne',
     theBreachIsCrossBorderInNature: 'Naruszenie ma charakter transgraniczny',
     countryEu: 'Zaznacz kraje Europejskiego Obszaru Gospodarczego, których dotyczy naruszenie: ',
     austria: 'Austria',
     cyprus: 'Cypr',
     finland: 'Finlandia',
     netherlands: 'Holandia',
     lithuania: 'Litwa',
     germany: 'Niemcy',
     slovakia: 'Słowacja',
     greatBritain: 'Wielka Brytania',
     belgium: 'Belgia',
     czechRepublic: 'Czechy',
     france: 'Francja',
     ireland: 'Irlandia',
     luxembourg: 'Luksemburg',
     norway: 'Norwegia',
     slovenia: 'Słowenia',
     italy: 'Włochy',
     bulgaria: 'Bułgaria',
     denmark: 'Niemcy',
     greece: 'Grecja',
     iceland: 'Islandia',
     latvia: 'Łotwa',
     portugal: 'Portugalia',
     sweden: 'Szwecja',
     croatia: 'Chorwacja',
     estonia: 'Estonia',
     spain: 'Hiszpania',
     liechtenstein: 'Liechtenstein',
     malta: 'Liechtenstein',
     romania: 'Rumunia',
     hungary: 'Węgry',
     sectionInformation: 'Informacja: ',
     conflictLabel: 'Uwaga',
     conflictDescSave:
          'Istnieje nowsza wersja formularza Zgłaszania naruszeń danych osobowych. Zachowaj swoje zmiany poza systemem i odśwież stronę, aby pobrać najnowszą wersję.',
     conflictDesc:
          'Istnieje nowsza wersja formularza Zgłaszania naruszeń danych osobowych. Odśwież stronę, aby pobrać najnowszą wersję.',
     clearAllText: 'Wyczyść',
     publicSectorSelect: {
          GOVERNMENT_ADMINISTRATION: 'Administracja rządowa',
          STATE_OWNED_ENTERPRISES: 'Przedsiębiorstwa państwowe',
          JUSTICE: 'Wymiar sprawiedliwości',
          PROSECUTORS_OFFICE: 'Prokuratura',
          UNIFORMED_AND_OFFICIAL_SERVICES: 'Służby mundurowe i służby specjalne',
          NATIONAL_TAX_ADMINISTRATION: 'Krajowa administarcja skarbowa',
          LOCAL_GOVERNMENT: 'Samorząd terytorialny ',
          SCHOOLS_KINDERGARTENS_NURSERIES: 'Szkoły, przedszkola, żłobki',
          UNIVERSITIES: 'Uczelnie wyższe',
          HEALTH_SERVICE: 'Służba zdrowia ',
          RESEARCH_INSTITUTIONS: 'Instytucje badawcze',
          CULTURAL_INSTITUTIONS: 'Instytucje kultury',
          SPORT_AND_RECREATION: 'Sport i rekreacja',
          PUBLIC_MEDIA: 'Media publiczne',
          POLITICAL_PARTY: 'Partie polityczne',
          STATE_FORESTS: 'Lasy państwowe',
          OTHER: 'Inne',
     },
     privateSectorSelect: {
          SCHOOLS_KINDERGARTENS_NURSERIES: 'Szkoły, przedszkola, żłobki',
          UNIVERSITIES: 'Uczelnie wyższe',
          TRADE: 'Handel',
          MARKETING: 'Marketing',
          REAL_ESTATE: 'Nieruchomości',
          INDUSTRY: 'Przemysł',
          ENERGY_SUPPLY: 'Dostawa energii',
          FINANCE_AND_BANKING: 'Finanse i bankowość',
          INSURANCE: 'Ubezpieczenia',
          TRANSPORT: 'Transport',
          AUTOMOTIVE: 'Motoryzacja',
          TOURISM: 'Turystyka',
          ASSOCIATIONS_AND_FOUNDATIONS: 'Stowarzyszenia i fundacje',
          HEALTH_SERVICE: 'Służba zdrowia',
          ART_AND_CULTURE: 'Sztuka i kultura',
          SCIENCE_AND_RESEARCH_INSTITUTES: 'Nauka i instytuty badawcze',
          TELECOMMUNICATION: 'Telekomunikacja',
          SPORT_AND_RECREATION: 'Sport i rekreacja',
          EMPLOYMENT: 'Zatrudnienie',
          PROFESSIONAL_SELF_GOVERNMENTS: 'Samorządy zawodowe',
          MEDIA: 'Media',
          IT_SERVICES: 'Usługi IT',
          AGRICULTURE_FORESTRY_FISHING: 'Rolnictwo, leśnictwo, rybołóstwo',
          OTHER: 'Inne',
     },
     uodosList: 'Lista naruszeń',
     newUodoLabel: 'Nowe zgłoszenie naruszenia danych osobowych',
     newUodo: 'Zgłoś naruszenie danych osobowych',
     id: 'ID',
     title: 'Tytuł',
     typeReport: 'Typ zgłoszenia',
     timeFromFindingToReporting: 'Czas od stwierdzenia do zgłoszenia',
     dateOfDiscoveryOfTheInfringement: 'Data stwierdzenia naruszenia',
     categoryDataPerson: 'Kategoria danych osobowych',
     art9ofRODO: 'Szczególne kategorie danych - art.9 RODO',
     art10ofRODO: 'Dane dotyczące wyroków skazujących i czynów zabronionych - art. 10 RODO',
     highRisk: 'Wysokie ryzyko',
     crossborderInfringement: 'Naruszenie transgraniczne',
     filingDate: 'Data zgłoszenia',
     haveDataSubjectBeenNotified: 'Czy zawiadomiono osoby, których dane dotyczą?',
     fullNameAdminSearch: 'Nazwa administratora danych',
     issuedByEntity: 'Podmiot zgłaszający',
     actions: 'Akcje',
     true: 'Tak',
     false: 'Nie',
};
