import { EntitiesAffectedInfringementDTO } from './entities-affected-infringement-dto';
import { PersonsAuthorizedRepresentAdministratorDTO } from './persons-authorized-represent-administrator-dto';

/* tslint:disable */
export interface DescriptionDTO {
     optionalSign?: string;
     registrationComplet?: boolean;
     registrationBegin?: boolean;
     registrationCompletModify?: boolean;
     addDatereopen?: number;
     addDateold?: number;
     addTaskSignUodo?: string;
     theViolationHasBeenReportedOtherCoutry?: boolean;
     theViolationHasBeenReportedOtherCoutryDesc?: string;
     theViolationHasBeenReported?: boolean;
     addNameDepart?: string;
     addSignatureRegistration?: string;
     fullNameAdmin?: string;
     regon?: string;
     nip?: string;
     krs?: string;
     street?: string;
     numberHouse?: string;
     numberflat?: string;
     city?: string;
     indicateTheDateOfThePlannedNotification?: number;
     postCode?: string;
     provinceAdministrativeArea?: string;
     countyAdministrativeArea?: string;
     countyAdministrativeArea1?: string;
     country?: string;
     applicationCompletedTheRepresentative?: boolean;
     dataProtectionOfficer?: string;
     phoneNumber?: string;
     mail?: string;

     personsAuthorizedRepresentAdministratorDTO: PersonsAuthorizedRepresentAdministratorDTO[];
     entitiesAffectedInfringementDTO: EntitiesAffectedInfringementDTO[];

     anInspectorHasNotBeenAppointed?: boolean;
     descriotionSection2e?: string;
     dateDiscoveryInfringement?: number;
     methodDeterminingViolation?: string;
     dateInformationSubject?: number;
     reasonsForDelay?: string;
     dateTime3b?: number;
     dateTimeEnd3b?: number;
     section4a?: string;
     section4bcheckboxA?: boolean;
     section4bcheckboxB?: boolean;
     section4bcheckboxC?: boolean;
     section4bcheckboxD?: boolean;
     section4bcheckboxE?: boolean;
     section4bcheckboxF?: boolean;
     section4bcheckboxG?: boolean;
     section4bcheckboxH?: boolean;
     section4bcheckboxI?: boolean;
     section4bcheckboxJ?: boolean;
     section4bcheckboxK?: boolean;
     section4bcheckboxL?: boolean;
     section4bcheckboxM?: boolean;
     descriptionSection4Cb?: string;
     descriptionSection4Cc?: string;
     internalActionUnintentional?: boolean;
     internalActionIntentional?: boolean;
     externalActionUnintentional?: boolean;
     externalActionIntentional?: boolean;
     breachOfDataConfidentiality?: boolean;
     dataIntegrityBreach?: boolean;
     descDataIntegrityBreach?: boolean;
     section4FKids?: boolean;
     approximateNumberOfPeopleBreached?: string;
     surnamesAndNames?: boolean;
     namesParents?: boolean;
     birthData?: boolean;
     numberaAccountBank?: boolean;
     adressliving?: boolean;
     pesel?: boolean;
     addressMail?: boolean;
     loginPassword?: boolean;
     dataFromMoney?: boolean;
     surnameMother?: boolean;
     serialNumberPersonallDocument?: boolean;
     phoneNumer?: boolean;
     imagePerson?: boolean;
     other?: boolean;
     otherdesc?: string;
     dataAboutRacialEthnicOrigin?: boolean;
     dataAboutPolitic?: boolean;
     dataAboutReligion?: boolean;
     dataAboutSocjal?: boolean;
     dataAboutSexual?: boolean;
     dataAboutHealth?: boolean;
     dataAboutGenetic?: boolean;
     dataAboutBiometric?: boolean;
     dataAboutGuiltyverdicts?: boolean;
     dataAboutProhibitedActs?: boolean;
     dataAboutOther?: boolean;
     dataAboutOtherDesc?: string;
     employes?: boolean;
     users?: boolean;
     studentsHightSchool?: boolean;
     students?: boolean;
     uniformedServices?: boolean;
     customers?: boolean;
     customersPublic?: boolean;
     patients?: boolean;
     kids?: boolean;
     peopleWithSpecialNeeds?: boolean;
     detailedDescriptionOfCategoriesPersonsAffectedThebreach?: string;
     lossControlOverPersonalData?: boolean;
     limitationAbilityToExerciseRightsRodo?: boolean;
     limitationAbilityToExerciseRights?: boolean;
     discrimination?: boolean;
     identityTheftFraud?: boolean;
     financialLoss?: boolean;
     infringementGoodName?: boolean;
     lossConfidentialityPersonalDataProtectedProfessionalSecrecy?: boolean;
     unauthorizedReversalPseudonymization?: boolean;
     section8aOthers?: boolean;
     section8aOthersDesc?: string;
     section8B?: boolean;
     justification?: string;
     section9?: string;
     section9a?: string;
     section9b?: string;
     section9c?: string;
     section10Notice?: boolean;
     section10true?: boolean;
     section10IndwidualTrue?: boolean;
     section10IndwidualTrue2?: boolean;
     section10IndwidualFalse?: boolean;
     theyWillNotBeNotifiedBecause?: boolean;
     ihaventRatedItYet?: boolean;
     appropriateTechnicalMeasuresHaveBeenImplementedBeforeTheViolation?: boolean;
     measuresWereTakenFollowingTheBreach?: boolean;
     noHighRiskWasFound?: boolean;
     indicateTheDateNotification?: number;
     indicateTheDateOfThePlannedNotification1?: number;
     numberOfPeopleNotified?: string;
     iDoNotYetKnowDateWhenIntendToNotifyDataSubjects?: boolean;
     meansOfCommunicationUsedToNotifyDataSubject?: string;
     includeDheAnonymized?: string;
     theBreachIsCrossBorderInNature?: boolean;

     descWritelaw?: string;
     descDetailedDescriptionOfCategoriesPersonsAffectedThebreach?: string;
     namesParents1?: string;
     approximateNumberOfPeopleBreachedEntry?: string;
     dataAvailabilityViolation?: string;
     descriptionSection4Ca?: string;
     forSectorPublic?:
          | 'GOVERNMENTADMINISTRATION'
          | 'STATEOWNEDENTERPRISES'
          | 'JUSTICE'
          | 'PROSECUTORSOFFICE'
          | 'UNIFORMEDANDOFFICIALSERVICES'
          | 'NATIONALTAXADMINISTRATION'
          | 'LOCALGOVERNMENT'
          | 'SCHOOLKINDERGARTENNURSERIES'
          | 'UNIVERSITIES'
          | 'HEALTHSERVICE'
          | 'RESEARCHINSTITUTIONS'
          | 'CULTURALINSTITUTIONS'
          | 'SPORTSANDRECREATION'
          | 'PUBLICMEDIA'
          | 'POLITICALPARTY'
          | 'STATEFORESTS'
          | 'OTHER';
     forSectorPrivate?:
          | 'SCHOOLSKINDERGARTENSNURSERIES'
          | 'UNIVERSITIES'
          | 'TRADE'
          | 'MARKETING'
          | 'REALESTATE'
          | 'INDUSTRY'
          | 'ENERGYSUPPLY'
          | 'FINANCEANDBANKING'
          | 'INSURANCE'
          | 'TRANSPORT'
          | 'AUTOMOTIVE'
          | 'TOURISM'
          | 'ASSOCIATIONSANDFOUNDATIONS'
          | 'HEALTHSERVICE'
          | 'ARTANDCULTURE'
          | 'SCIENCEANDRESEARCHINSTITUTES'
          | 'TELECOMMUNICATION'
          | 'SPORTSANDRECREATION'
          | 'EMPLOYMENT'
          | 'PROFESSIONALSELFGOVERNMENTS'
          | 'MEDIA'
          | 'ITSERVICES'
          | 'AGRICULTUREFORESTRYFISHING'
          | 'OTHER';
     communeAdministrativeArea?: string;
     descSection4a?: string;
     nameDateContact?: string;
     austria?: boolean;
     cyprus?: boolean;
     finland?: boolean;
     netherlands?: boolean;
     lithuania?: boolean;
     germany?: boolean;
     slovakia?: boolean;
     greatBritain?: boolean;
     belgium?: boolean;
     czechRepublic?: boolean;
     france?: boolean;
     ireland?: boolean;
     luxembourg?: boolean;
     norway?: boolean;
     slovenia?: boolean;
     italy?: boolean;
     bulgaria?: boolean;
     denmark?: boolean;
     greece?: boolean;
     iceland?: boolean;
     latvia?: boolean;
     portugal?: boolean;
     sweden?: boolean;
     croatia?: boolean;
     estonia?: boolean;
     spain?: boolean;
     liechtenstein?: boolean;
     malta?: boolean;
     romania?: boolean;
     hungary?: boolean;
}
